package com.soho.codegen.domain;

import com.soho.mybatis.crud.domain.IDEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table login_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class LoginLog implements IDEntity<Long> {
    /**
     * Database Column Remarks:
     *   ID
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   登录时间
     */
    private Long logtime;

    /**
     * Database Column Remarks:
     *   登录IP地址
     */
    private String logaddr;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private Long ctime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getLogtime() {
        return logtime;
    }

    public void setLogtime(Long logtime) {
        this.logtime = logtime;
    }

    public String getLogaddr() {
        return logaddr;
    }

    public void setLogaddr(String logaddr) {
        this.logaddr = logaddr == null ? null : logaddr.trim();
    }

    public Long getCtime() {
        return ctime;
    }

    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }
}