package com.soho.codegen.domain;

import com.soho.mybatis.crud.domain.IDEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zip_message
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class ZipMessage implements IDEntity<Long> {
    private Long id;

    private Long userId;

    private String dburl;

    private String tables;

    private String filePath;

    private String fileName;

    private Long fileSize;

    private Long ctime;

    private Long utime;

    /**
     * Database Column Remarks:
     *   1.正常 2.删除
     */
    private Integer state;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getDburl() {
        return dburl;
    }

    public void setDburl(String dburl) {
        this.dburl = dburl == null ? null : dburl.trim();
    }

    public String getTables() {
        return tables;
    }

    public void setTables(String tables) {
        this.tables = tables == null ? null : tables.trim();
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Long getCtime() {
        return ctime;
    }

    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    public Long getUtime() {
        return utime;
    }

    public void setUtime(Long utime) {
        this.utime = utime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }
}